# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 3
    y: 3
  opacity: 0.85
  gtk_theme_variant: dark

scrolling.history: 20000

# font tbd

font:
  size: 7.0

colors.primary:
  background: '#000000'
  foreground: '#e8e8e8'

cursor.style:
  shape: Beam
  blinking: On

mouse.hide_while_typing: true
