#!/bin/sh

# edit zsh config file
alias zcfg="vim $HOME/.zshrc"
# edit bash config file
alias bcfg="vim $HOME/.bashrc"
# edit this file itself
alias vals="vim $HOME/dotfiles/shaliases"
# edit functions
alias vfuncs="vim $HOME/dotfiles/shfuncs"

# echo this file
alias als="cat $HOME/dotfiles/shaliases"
# echo only options on this file
alias also="cat $HOME/dotfiles/shaliases | grep --color=never \"alias \""

# open vim
alias v=vim

# sync and update pacman packages
alias upd="sudo pacman -Syu"

# upd and reboot
alias updr="sudo pacman -Syu ; reboot"

# install with pacman
alias pi="sudo pacman -S"
# install from local .pkg.tar.zst
alias pil="sudo pacman -U"
# remove package and dependencies
alias pr="sudo pacman -Rs"
# search from official repos
alias psc="pacman -Ss"
# search local packages
alias pq="pacman -Q"

# sync and update AUR packages
alias upds="paru -Syu"
# install from AUR (with paru)
alias pai="paru -S"
# search from AUR
alias pasc="paru -Ss"

# remove reclusively ("for real")
alias rmd="rm -fr"

# move to previous directory
alias pv="cd .."
# Self explainatory.
alias ll="ls -l"

# enable systemd service (now)
alias syse="sudo systemctl enable --now"
# disable systemd service (now)
alias sysd="sudo systemctl disable --now"
# start systemd service for this session
alias sysst="sudo systemctl start"
# stop systemd service for this session
alias syssp="sudo systemctl stop"

# clone git repo
alias gcl="git clone"
# add folder to git repo
alias gad="git add ."
# make commit to git repo
alias gcmm="git commit -m"
# send git commit
alias gph="git push"

# full make (clean, compile and install)
alias mkef="make clean && make -j4 && sudo make install"
# Process to generate cmake environment without prefix
alias cemakelcl="mkdir Build && cd Build && cmake .."
# Process to generate cmake environment with prefix /usr
alias cemake="mkdir Build && cd Build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr"

# start X session from $HOME/.xinitrc
alias x="startx"

# Get number of elements in a diretory
alias howmany="ls | wc -l"
# Get number of elements in a directory including hidden
alias howmanyall="ls -a | wc -l"
