#!/bin/sh

# shalises
# Shell alias dumpster (Source on shell's .rc)

# # #	EDIT SHELL FILES
# edit zsh config file
alias zcfg="vim $HOME/.zshrc"
# edit bash config file
alias bcfg="vim $HOME/.bashrc"
# edit this file itself
alias vals="vim $HOME/dotfiles/shaliases"
# edit functions
alias vfuncs="vim $HOME/dotfiles/shfuncs"

# echo this file
alias als="cat $HOME/dotfiles/shaliases"
# echo only options on this file ('alias' prints all of them)
alias also="cat $HOME/dotfiles/shaliases | grep --color=never \"alias \""

# # #	OPEN PROGRAMS
# open vim
alias v=vim

# # #	PACMAN AND PARU COMMANDS
# sync and update pacman packages
alias upd="sudo pacman -Syu"
# upd and reboot
alias updr="sudo pacman -Syu ; reboot"
# install with pacman
alias pi="sudo pacman -S"
# install from local .pkg.tar.zst
alias pil="sudo pacman -U"
# remove package and dependencies
alias pr="sudo pacman -Rs"
# search from official repos
alias psc="pacman -Ss"
# search local packages
alias pq="pacman -Q"

# sync and update AUR packages
alias upds="paru -Syu"
# install from AUR (with paru)
alias pai="paru -S"
# search from AUR
alias pasc="paru -Ss"

# # #	PLAY WITH FILES AND DIRECTORIES
# remove reclusively
alias rmd="rm -fr"
# move to previous directory
alias pv="cd .."
# Self explainatory.
alias ll="ls -l"
# Get number of elements in a diretory
alias howmany="ls | wc -l"
# Get number of elements in a directory including hidden
alias howmanyall="ls -a | wc -l"

# # #	SYSTEMD AND OPENRC COMMANDS
# enable systemd service (now)
alias syse="sudo systemctl enable --now"
# disable systemd service (now)
alias sysd="sudo systemctl disable --now"
# start systemd service for this session
alias sysst="sudo systemctl start"
# stop systemd service for this session
alias syssp="sudo systemctl stop"

# rc-update
alias rcu="rc-update"
# rc-service
alias rcs="rc-service"

# # #	GIT COMMANDS
# clone git repo
alias gcl="git clone"
# add folder to git repo
alias gad="git add ."
# make commit to git repo
alias gcmm="git commit -m"
# send git commit
alias gph="git push"
# Pull from git repo
alias gpl="git pull"

# # #	COMPILING COMMANDS
# full make (clean, compile and install)
alias mkef="make clean && make -j8 && sudo make install"
# Process to generate cmake environment without prefix
alias cemakelcl="mkdir Build && cd Build && cmake .."
# Process to generate cmake environment with prefix /usr
alias cemake="mkdir Build && cd Build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr"
# make config.h for suckless style programs
alias mkcfg="rm config.h && make config.h"

# start X session from $HOME/.xinitrc
alias x="startx"
