#!/bin/sh 

# shfuncs.
# Shell function dumpster (Source on shell's .rc).

DOTFDIR=$HOME/dotfiles
VALS=$DOTFDIR/shaliases

aliasadd() {
	read -p "Alias name: " name
	read -p "Alias function: " func
	read -p "(Optional) Function description: " desc
	
	if [ ! $desc == '' ]; then
		printf "\n# %s\nalias %s=\"%s\"\n" "$desc" "$name" "$func" >> $VALS
	else
		printf "\nalias %s=\"%s\"\n" "$name" "$func" >> $VALS
	fi
} # Add an alias

aliasdel() {
	read -p "Alias to delete: " ALIAS
	DELETE=$(grep -B1 $ALIAS $VALS)
	AVALIBLE=$(grep "alias " $VALS | awk '{print $2}' | cut -f1 -d"=")

	if [[ ! $(echo "$AVALIBLE" | grep -w "$ALIAS") ]]; then
		echo "$ALIAS is not a listed alias."
		return 1
	fi

	printf "The following lines will be deleted:\n\n%s\n" "$DELETE"
	read -p "Confirm removal (type 'yes') " CONFIRM
	if [ $CONFIRM == 'yes' ]; then
		sed "s/$DELETE//"
	fi
	return 0
}

wtar() {
	LINK=$1
	TAR=$(echo $LINK | sed 's/.*\///')
	DIR=$(tar -tf $TAR | head -n 1)
	
	wget $LINK
	tar -axpvf $TAR
	mv $TAR $DIR
} # Get a tarball from the web, extract it and move the tarball to the extracted directory
