#!/bin/sh 

# shfuncs.
# Shell function dumpster (Source on shell's .rc).

DOTFDIR=$HOME/dotfiles
VALS=$DOTFDIR/shaliases

aliasadd() {
	if [[ ! $1 == '' ]]; then
		name=$1
	else
		read -p "Alias name: " name
	fi
	read -p "Alias function: " func
	read -p "(Optional) Function description: " desc
	
	if [[ ! $desc == '' ]]; then
		printf "\n# %s\nalias %s=\"%s\"\n" "$desc" "$name" "$func" >> $VALS
		return 0
	else
		printf "\nalias %s=\"%s\"\n" "$name" "$func" >> $VALS
		return 0
	fi
} # Add an alias

aliasdel() {
	if [[ ! $1 == '' ]]; then
		ALIAS=$1
	else
		read -p "Alias to delete: " ALIAS
	fi

	DELETE=$(grep -B1 $ALIAS $VALS)
	AVALIBLE=$(grep "alias " $VALS | awk '{print $2}' | cut -f1 -d"=")

	if [[ ! $(echo "$AVALIBLE" | grep -w "$ALIAS") ]]; then
		echo "$ALIAS is not a listed alias."
		return 1
	fi

	printf "The following lines will be deleted:\n\n%s\n" "$DELETE"
	read -p "Confirm removal (type 'yes') " CONFIRM
	if [[ $CONFIRM == 'yes' ]]; then
		sed "s/$DELETE//" $VALS
	fi
	return 0
} # Delete an alias

wtar() {
	LINK=$1
	TAR=$(echo $LINK | sed 's/.*\///')
	
	wget $LINK && tar -axpvf $TAR

	DIR=$(tar -tf $TAR | head -n 1)
	mv $TAR $DIR
	return 0
} # Get a tarball from the web, extract it and move the tarball to the extracted directory

acst() {
	ID=$1
	if [[ ! $ID == "acestream://*" ]]; then
		ID="acestream://$ID"
	fi
	exec acestream-launcher --player mpv $ID
	return 0
} # Open acestream from IDs instead of typing the whole thing
