#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Configuration
setxkbmap es &
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1 &
xsetroot -cursor_name left_ptr &

# Autostart programs
feh --bg-fill --randomize $HOME/Imágenes/.bg/* &
exec bspwmbar &
exec picom &
exec blueman-applet &
