#! /bin/sh

# Config file for bspwm-rounded-corners-git
# https://aur.archlinux.org/packages/bspwm-rounded-corners-git

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius	10

# Start apps tiled or floating
bspc rule -a Zathura state=tiled
bspc rule -a Gscreenshot rectangle=700x600+610+240 state=floating focus=on
# bspc rule -a Virt-manager rectangle=400x600+760+240 state=floating focus=on

# Configuration
setxkbmap es &
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1 &
xsetroot -cursor_name left_ptr &

# Autostart programs
feh --bg-fill --randomize $HOME/Imágenes/pawa.jpg &
exec picom &
