#!/bin/sh

# shalises
# Shell alias dumpster (Source on shell's .rc)

DOTF=$HOME/code/git/dotfiles/zshmod/
EDITOR=nvim

# # #	EDIT SHELL FILES
# edit zsh config file
alias zcfg="$EDITOR $DOTF/zshrc"
# edit bash config file
alias bcfg="$EDITOR $HOME/.bashrc"
# edit this file itself
alias vals="$EDITOR $DOTF/shaliases"
# edit functions
alias vfuncs="$EDITOR $DOTF/shfuncs"
# edit variables
alias vvars="$EDITOR $DOTF/shvars"

# echo this file
alias als="cat $DOTF/shaliases"
# echo only options on this file ('alias' prints all of them)
alias also="grep --color=never \"alias \" $DOTF/shaliases"

# # #	OPEN PROGRAMS
# open nvim
alias v=$EDITOR

# # #	PACKAGE MANAGER COMMANDS
# sync and update pacman packages
alias upd="sudo pacman -Syu --noconfirm"
## alias upd="sudo xbps-install -Su"
# alias upd="sudo apt update && sudo apt upgrade"
# alias upd="sudo pkg update"
# install with pacman
alias pi="sudo pacman -S"
## alias pi="sudo xbps-install -S"
# alias pi="sudo apt install"
# alias pi="sudo pkg install"
# install from local .pkg.tar.zst
alias pil="sudo pacman -U"
## alias pil="sudo xbps-install --repository ."
# alias pil="sudo dpkg -i"
# install from xbps-src
## alias pil-src="sudo xbps-install --repository hostdir/binpkgs"
# remove package and dependencies
alias pr="sudo pacman -Rs"
## alias pr="sudo xbps-remove -Ro"
# alias pr="sudo apt-get purge"
# alias pr="sudo pkg delete -f"
# remove orphans
alias rm-orphs="pacman -Qtdq | sudo pacman -Rns -"
## alias rm-orphs="sudo xbps-remove -O"
# alias rm-orphs="sudo apt-get autoremove"
# alias rm-orphs="sudo pkg autoremove"
# search from official repos
alias psc="pacman -Ss"
## alias psc="xbps-query -Rs"
# alias psc="apt search"
# alias psc="pkg search"
# search local packages
alias pq="pacman -Q"
## alias pq="xbps-query -s"
# alias pq="apt list --installed"
# alias pq="pkg info"
# Sync pacman repositories
alias psy="sudo pacman -Sy"
# Install as dependency
alias pi-dep="sudo pacman -S --asdeps"

# sync and update AUR packages
alias upds="paru -Syu"
# install from AUR (with paru)
alias pai="paru -S"
# search from AUR
alias pasc="paru -Ss"

# # #	PLAY WITH FILES AND DIRECTORIES
# remove reclusively
# alias rmd="rm -fr"
# move to previous directory
alias pv="cd .."
# Self explainatory.
alias ls="/bin/ls --color='auto'"
alias ll="/bin/ls -lh --color=auto"
# Get number of elements in a diretory
alias howmany="ls | wc -l"
# Get number of elements in a directory including hidden
alias howmanyall="ls -A | wc -l"
# Bunch of dirs
alias bg="cd $HOME/docs/pics/.bg && ls"
alias dw="cd $HOME/docs/downs && ls"
alias dm="cd $HOME/docs && ls"
alias ap="cd $HOME/docs/apuntes/2023-1/PRU/markdown && ls"
alias gm="cd $HOME/Games && ls"
alias dotf="cd $DOTF && ls"
alias rps="cd $HOME/code/repos && ls"

# # #	SYSTEMD AND OPENRC COMMANDS
# enable systemd service (now)
alias syse="sudo systemctl enable --now"
# disable systemd service (now)
alias sysd="sudo systemctl disable --now"
# start systemd service for this session
alias sysst="sudo systemctl start"
# stop systemd service for this session
alias syssp="sudo systemctl stop"

# rc-update
# alias rcu="rc-update"
# rc-service
# alias rcs="rc-service"
#
# # # TODO: FreeBSD rc.conf

# # #	GIT COMMANDS
# clone git repo
alias gcl="git clone"
# gcl but recursive
alias gclr="git clone --recursive"
# add folder to git repo
alias gad="git add ."
# make commit to git repo
alias gcmm="git commit -m"
# send git commit
alias gph="git push"
# Pull from git repo
alias gpl="git pull"

# # #	COMPILING COMMANDS
# full make (clean, compile and install)
alias mkef="make clean && make -j8 && sudo make install"
# Process to generate cmake environment without prefix
alias cemakelcl="mkdir Build && cd Build && cmake .."
# Process to generate cmake environment with prefix /usr
alias cemake="mkdir Build && cd Build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr"
# make config.h for suckless style programs
alias mkcfg="rm config.h; make config.h"
# cargo build
alias cgb="cargo build -j8"
# cargo install
alias cgi="cargo install"

# start X session from $HOME/.xinitrc
alias x="startx"

# Run pridefetch with the tumblr gay flag by default
alias pridefetch="/usr/local/bin/pridefetch -f gay"

# Run LF with the lfimg script (https://github.com/cirala/lfimg)
# alias lf="$HOME/.local/bin/lfrun"
# alias lf-base="/usr/bin/lf"

# Run Nut
alias nut="python3 $HOME/code/repos/nut/nut_gui.py"

# copy tex template
alias textl="cp $HOME/docs/template.tex"

# Open zsh history file
alias zhist="$EDITOR $HOME/.zhistfile"

# Open awesome config directory
alias aw="cd $HOME/.config/awesome"
# Open awesome config file
alias awf="$EDITOR $HOME/.config/awesome/rc.lua"

# ed with prompt
alias ed="/usr/bin/rlwrap /bin/ed -v -p'ed> '"

# run python3
alias py="python3"

# date(1) but the output is with english locale
alias endate="LANG=en_US.UTF-8 date"

# open webcam in mpv
alias webcam="mpv --profile=low-latency --untimed /dev/video0"

# edit nvim config
alias nvimcfg="$EDITOR $HOME/.config/nvim/"

# make executable
alias chmox="chmod +x"

# re-source rc file
alias so="source ~/.zshrc"

# silent curl
alias curs="curl -s"

# Change to ~/code directory
alias cood="cd $HOME/code/src"

# Change directory to code projects folder
alias proj="cd $HOME/code/proj"

# Open markdown index
alias index="$EDITOR index.md"

alias ngrep="grep -n"

alias cat="bat --paging=never"
alias ccat="/bin/cat"

alias tfg="cd $HOME/docs/apuntes/2023-1/TFG"
