#!/bin/sh

export PATH="$PATH:$HOME/.local/bin"
export EDITOR=nvim
export FILEMANAGER=ranger
export PDFVIEWER=zathura
export TEXMFDIST=/usr/share/texmf-dist

export APUNTES=$HOME/Documentos/apuntes

export CARGO_HOME=$HOME/code/.cargo
export RUSTUP_HOME=$HOME/code/.rustup

export NODE_PATH=$HOME/code/.node_modules

export GRADLE_USER_HOME=$HOME/code/.gradle

export inpush=1
